import type {NextPage} from 'next';
import Head from 'next/head';
import {trpc} from '../utils/trpc';
import {BookScenario} from '../components/book-scenario';
import {Navbar} from '../components/navbar';

const Book: NextPage = () => {
	const scenarioQuery = trpc.scenario.all.useQuery();

	const mutation = trpc.game.create.useMutation();
	const handleCreate = async () => {
		await mutation.mutateAsync({
			scenario: '',
			title: '',
			content: '',
			numberOfPlayers: 0,
			reservationDate: '',
			room: 0,
		});
	};

	console.log(scenarioQuery.data);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
				{scenarioQuery.data ? (
					scenarioQuery.data?.map(scenario => (
						<BookScenario scenario={scenario} />
					))
				) : (
					<div>Loading...</div>
				)}
			</main>
		</>
	);
};

export default Book;
