import type {GetServerSideProps} from 'next';
import Head from 'next/head';
import {Navbar} from '../components/navbar';
import {Disclosure} from '@headlessui/react';
import {prisma} from '@paradox/db';
import {Faq} from '@prisma/client';

type Props = {
	faq: Faq[];
};
const Faq = ({faq}: Props) => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
				{faq.map(item => (
					<Disclosure key={item.id}>
						<Disclosure.Button className='py-2'>
							{item.question}
						</Disclosure.Button>
						<Disclosure.Panel className='text-gray-500'>
							{item.answer}
						</Disclosure.Panel>
					</Disclosure>
				))}
			</main>
		</>
	);
};

export const getServerSideProps: GetServerSideProps = async () => {
	const faq = await prisma.faq.findMany();
	return {
		props: {
			faq,
		},
	};
};

export default Faq;
