import type {NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import {Navbar} from '../components/navbar';

const Faq: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
				<Link href={'/admin'}>
					<a className='text-2xl font-bold text-gray-800'>Page Admin</a>
				</Link>
			</main>
		</>
	);
};

export default Faq;
