import type {NextPage} from 'next';
import Head from 'next/head';
import {Navbar} from '../components/navbar';
import {Disclosure} from '@headlessui/react';

const Faq: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
				<Disclosure>
					<Disclosure.Button className='py-2'>
						Is team pricing available?
					</Disclosure.Button>
					<Disclosure.Panel className='text-gray-500'>
						Yes! You can purchase a license that you can share with your entire
						team.
					</Disclosure.Panel>
				</Disclosure>
			</main>
		</>
	);
};

export default Faq;
