import type {NextPage} from 'next';
import Head from 'next/head';
import {trpc} from '../utils/trpc';
import type {inferProcedureOutput} from '@trpc/server';
import type {AppRouter} from '@paradox/api';
import Link from 'next/link';
import {ScenarioCard} from '../components/scenario-card';
import {Navbar} from '../components/navbar';
import {WebLayout} from '../components/layout/web-layout';

const Home: NextPage = () => {
	const postQuery = trpc.scenario.all.useQuery();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<WebLayout>
				<main className='container flex flex-col items-center min-h-screen py-16 mx-auto'>
					<Link href={'/admin'}>
						<a className='text-2xl font-bold text-gray-800'>Page Admin</a>
					</Link>
					<div className='flex flex-col gap-2'>
						{postQuery.data?.map(post => (
							<ScenarioCard key={post.id} scenario={post} />
						))}
					</div>
				</main>
			</WebLayout>
		</>
	);
};

export default Home;
